name: Build GO container
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      organization: ${{ steps.repository.outputs.organization }}
      project: ${{ steps.repository.outputs.project }}
    steps:
      - name: Repository
        id: repository
        run: |
          input="${{ github.repository }}"
          read -r var1 var2 <<< "$(sed -E 's|(.*)/(.*)|\1 \2|' <<< "$input")"
          var1_lower="${var1,,}"
          var2_lower="${var2,,}"
          echo "organization=${var1_lower}" >> $GITHUB_OUTPUT
          echo "project=${var2_lower}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - darwin/amd64
          - darwin/arm64
    steps:
      - name: Set environment
        run: |
          echo "ORGANIZATION=${{ needs.setup.outputs.organization }}" >> $GITHUB_ENV
          echo "PROJECT=${{ needs.setup.outputs.project }}" >> $GITHUB_ENV
      - name: TEST
        run: |
          echo "$PROJECT"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set cache name
        id: cache-name
        run: |
          echo "cache-name=${PROJECT}-cache-${{ matrix.platform }}" | sed 's:/:-:g' >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ${PROJECT}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=local,dest=/tmp/${PROJECT}-cache,mode=max
      - name: Upload cache
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.cache-name.outputs.cache-name }}
          path: /tmp/$PROJECT-cache
          if-no-files-found: error
          retention-days: 1

  push:
    runs-on: ubuntu-latest
    needs:
      - setup
      - build
    steps:
      - name: Set environment
        run: |
          echo "ORGANIZATION=${{ needs.setup.outputs.organization }}" >> $GITHUB_ENV
          echo "PROJECT=${{ needs.setup.outputs.project }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download cache
        uses: actions/download-artifact@v3
        with:
          path: /tmp/${PROJECT}-cache
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            quay.io/${ORGANIZATION}/${PROJECT}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Login to QUAY.IO
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
            darwin/amd64
            darwin/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=gha,mode=max