name: Build GO container
on:
  workflow_call:
    secrets:
      QUAY_USERNAME:
        required: false
      QUAY_TOKEN:
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: Cloud-for-You/github-workflows/.github/workflows/release-please.yaml@main

  # Predelat na reusable workflow a nasledne zaradit flow, ktere provede napriklad semantic testy,
  # aby byly splneny prerekvizity pro dokumentovani zmen
  debug:
    runs-on: ubuntu-latest 
    needs:
      - release
    steps:
      - name: DEBUG setup output
        shell: bash
        run: |
          echo "Organization: ${{ needs.release.outputs.organization }}"
          echo "Project: ${{ needs.release.outputs.project }}"
          echo "Release_created: ${{ needs.release.outputs.release_created }}"
          echo "Release_SHA: ${{ needs.release.outputs.release_sha }}"

  build:
    runs-on: ubuntu-latest
    needs:
      - release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    steps:
      - name: Test step
        run: |
          echo "Provedeme build aplikace"


