name: Build GO container
on:
  workflow_call:
    secrets:
      QUAY_USERNAME:
        required: false
      QUAY_TOKEN:
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: Cloud-for-You/github-workflows/.github/workflows/release-please.yaml@main

  debug:
    runs-on: ubuntu-latest 
    needs:
      - release
    steps:
      - name: DEBUG setup output
        shell: bash
        run: |
          echo "Organization: ${{ needs.release.outputs.organization }}"
          echo "Project: ${{ needs.release.outputs.project }}"
          echo "Release: ${{ needs.release.outputs.release_sha }}"

  build:
    runs-on: ubuntu-latest
    needs:
      - release
    if: ${{ needs.release.outputs.release_sha == 'true' }}
    steps:
      - name: Test step
        run: |
          echo "Provedeme build aplikace"


