name: Build GO container
on:
  workflow_call:
    secrets:
      QUAY_USERNAME:
        required: false
      QUAY_TOKEN:
        required: false

jobs:
  releases:
    uses: Cloud-for-You/github-workflows/.github/workflows/releases.yaml@main

  debug:
    runs-on: ubuntu-latest 
    needs:
      - releases
    steps:
      - name: DEBUG setup output
        shell: bash
        run: |
          echo "Organization: ${{ needs.releases.outputs.organization }}"
          echo "Project: ${{ needs.releases.outputs.project }}"
          echo "Release: ${{ needs.releases.outputs.release }}"
