name: Prepare release variables
on:
  workflow_call:
    outputs:
      organization:
        description: "Organization (eg. folder in docker registry)"
        value: ${{ jobs.variables.outputs.organization }}
      project:
        description: "Project name (eg. container name)"
        value: ${{ jobs.variables.outputs.project }}
      version:
        description: "Application release version"
        value: ${{ jobs.variables.outputs.version }}
      tag:
        description: "Application release tag (eg. Tag for docker container)"
        value: ${{ jobs.variables.outputs.tag }}
      artifacts_url:
        description: "Where is uploaded releases artifacts"
        value: ${{ jobs.variables.outputs.upload_url }}

jobs:
  variables:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      organization: ${{ steps.repository.outputs.organization }}
      project: ${{ steps.repository.outputs.project }}
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag_name }}
      upload_url: ${{ steps.version.outputs.upload_url }}
    steps:
      - name: Repository
        id: repository
        run: |
          input="${{ github.repository }}"
          read -r var1 var2 <<< "$(sed -E 's|(.*)/(.*)|\1 \2|' <<< "$input")"
          echo "organization=${var1,,}" >> $GITHUB_OUTPUT
          echo "project=${var2,,}" >> $GITHUB_OUTPUT
      - name: Tag and version
        id: version
        uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: norelease
          tag_prefix: v
