name: Prepare release variables
on:
  workflow_call:

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      organization: ${{ steps.repository.outputs.organization }}
      project: ${{ steps.repository.outputs.project }}
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag_name }}
      artifacts_url: ${{ steps.version.outputs.upload_url }}
    steps:
      - name: Repository
        id: repository
        run: |
          input="${{ github.repository }}"
          read -r var1 var2 <<< "$(sed -E 's|(.*)/(.*)|\1 \2|' <<< "$input")"
          echo "organization=${var1,,}" >> $GITHUB_OUTPUT
          echo "project=${var2,,}" >> $GITHUB_OUTPUT
      - name: Tag and version
        id: version
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v
