name: Prepare release variables
on:
  workflow_call:
    outputs:
      organization:
        description: "Organization (eg. folder in docker registry)"
        value: ${{ jobs.variables.outputs.organization }}
      project:
        description: "Project name (eg. container name)"
        value: ${{ jobs.variables.outputs.project }}
      version:
        description: "Application release version"
        value: ${{ jobs.variables.outputs.version }}
      tag:
        description: "Application release tag (eg. Tag for docker container)"
        value: ${{ jobs.variables.outputs.tag }}
      upload_url:
        description: "Where is uploaded releases artifacts"
        value: ${{ jobs.variables.outputs.upload_url }}

jobs:
  variables:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      organization: ${{ steps.variables.outputs.organization }}
      project: ${{ steps.variables.outputs.project }}
      version: ${{ steps.variables.outputs.new_version }}
      tag: ${{ steps.variables.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set variables for release
        id: variables
        run: |
          setOutput() {
            echo "${1}=${2}" >> "$GITHUB_OUTPUT"
          }

          input="${{ github.repository }}"
          read -r var1 var2 <<< "$(sed -E 's|(.*)/(.*)|\1 \2|' <<< "$input")"

          currentBranch=$(git rev-parse --abbrev-ref HEAD)
          new_version=v0.0.0

          setOutput organization ${var1,,}
          setOutput project ${var2,,}
          setOutput version ${currentBranch}
          setOutput tag ${new_version}