name: Prepare release variables
on:
  workflow_call:
    outputs:
      organization:
        description: "Organization (eg. folder in docker registry)"
        value: ${{ jobs.variables.outputs.organization }}
      project:
        description: "Project name (eg. container name)"
        value: ${{ jobs.variables.outputs.project }}
      version:
        description: "Application release version"
        value: ${{ jobs.variables.outputs.version }}
      tag:
        description: "Application release tag (eg. Tag for docker container)"
        value: ${{ jobs.variables.outputs.tag }}
      upload_url:
        description: "Where is uploaded releases artifacts"
        value: ${{ jobs.variables.outputs.upload_url }}

jobs:
  variables:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      organization: ${{ steps.variables.outputs.organization }}
      project: ${{ steps.variables.outputs.project }}
      version: ${{ steps.variables.outputs.new_version }}
      tag: ${{ steps.variables.outputs.tag_name }}
    steps:
      - name: Get actual tag
        id: get_actual_tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")" >> $GITHUB_OUTPUT
      - name: Install prerequisite
        run: |
          npm install -g semver
      - name: Set variables
        id: variables
        run: |
          input="${{ github.repository }}"
          read -r var1 var2 <<< "$(sed -E 's|(.*)/(.*)|\1 \2|' <<< "$input")"
          level=${{ github.event.inputs.level || 'patch' }}
          new_version=$(semver bump $level ${{ steps.get_actual_tag.outputs.tag }})

          echo "organization=${var1,,}" >> $GITHUB_OUTPUT
          echo "project=${var2,,}" >> $GITHUB_OUTPUT
          echo "version=${new_version}" >> $GITHUB_OUTPUT
          echo "tag=${new_version}" >> $GITHUB_OUTPUT