name: Release Operator-SDK
on:
  workflow_call:
    inputs:
      OPERATOR_SDK_VERSION:
        description: "Version of Operator SDK Binary for installation"
        default: "v1.29.0"
        required: false
        type: string
      RUN_UNIT_TESTS:
        description: "Run unit tests will run the test target in the Makefile"
        default: false
        required: false
        type: boolean
      BUILD_KUSTOMIZE_PACKAGE:
        description: "Building kustomize artifact and release"
        default: false
        required: false
        type: boolean

jobs:
  setup:
    name: Setup
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    steps:
      # Get version for release artifacts
      - name: Get version
        id: version
        shell: bash
        run: |
          if [ "GITHUB_REF_TYPE" = "tag" ]; then
            VERSION="${GITHUB_REF#refs/*/v}"
          else
            VERSION="0.0.0-${GITHUB_REF_NAME//[\/]/-}.${GITHUB_SHA::8}"
          fi
          echo "image_version=$VERSION" >> $GITHUB_OUTPUT
          echo "kustomize_version=$VERSION" >> $GITHUB_OUTPUT
      # Checkout code from repository to workplace
      - name: Checkout
        uses: actions/checkout@v3

    outputs:
      image_version: ${{ steps.version.outputs.image_version }}
      kustomize_version: ${{ steps.version.outputs.kustomize_version }}

  build-image:
    name: Build image
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    needs:
      - setup
    env:
      IMAGE_VERSION: ${{ needs.setup.outputs.image_version }}
    steps:    
      # Build artifacts
      - name: Build Image
        shell: bash
        run: |
          echo "$IMAGE_VERSION"

  package-kustomize:
    name: Package kustomize
    needs:
      - setup
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    steps:
      - name: Foo
        shell: bash
        run: |
          echo "Bar"
  
  test-operator:
    name: Test operator
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    if: ${{ inputs.RUN_UNIT_TESTS }}
    needs:
      - setup
      - build-image
      - package-kustomize
    steps:
      - name: NOT DEFINED
        shell: bash
        run: |
          echo "JOB IS NOT DEFINED"
  
  release-version:
    name: Release version
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    needs:
      - setup
      - test-operator
    steps:
      - name: Release version
        shell: bash
        run: |
          echo "RELESE VERSION"


    